version: '3.8'

services:
  app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Specify your Dockerfile
    ports:
      - "80:8089"  # Redirect host port 80 to container port 8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Leave empty for no password
    depends_on:
      - db

  db:
    image: mysql:8.0  # Use MySQL version 8.0
    command: --default-authentication-plugin=mysql_native_password  # Required for MySQL 8 compatibility
    ports:
      - "3306:3306"  # Expose MySQL port
    environment:
      MYSQL_DATABASE: stationSki  # Name of the database
      MYSQL_ROOT_PASSWORD: ""  # Set root password here
      MYSQL_ALLOW_EMPTY_PASSWORD: yes  # Allow empty password if desired
    volumes:
      - db_data:/var/lib/mysql  # Volume for persistent MySQL data


volumes:
  db_data:  # Named volume for MySQL


