version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  gestion-station-ski:
    depends_on:
      - mysqldb
    image: benameurfedi/gestion-station-ski-1.0
    #build : ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db :