version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"  # Redirige le port 80 du host vers le port 8080 du conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/stationSki?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: # Laissez vide pour pas de mot de passe
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ROOT_PASSWORD: # Définissez ici un mot de passe pour l'utilisateur root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes # Si vous voulez laisser le mot de passe vide
    volumes:
      - db_data:/var/lib/mysql

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
    restart: always # Redémarre automatiquement si le conteneur échoue
    volumes:
      - nexus_data:/nexus-data

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    restart: always # Redémarre automatiquement si le conteneur échoue
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  db_data:
  nexus_data:
  sonarqube_data:
  sonarqube_extensions:
